Нужно больше функций
htmlacademy-javascript/2138449-kekstagram-28 pull request #2
Opened 2023-02-21 10:13 UTC by RamilJS

2023-02-21 15:20 UTC, Dima-Dim requested changes
Поправить замечания линтера.

2023-02-21 15:20 UTC, Dima-Dim commented on js/functions.js
> +	if (testString.length <= empty) {
Можно просто `return testString.length <= empty;`
А в `empty` будет что? Пустая строка?

2023-02-21 19:38 UTC, RamilJS commented on js/functions.js
> +	if (testString.length <= empty) {
В empty хранится разрешенная длинна строки, переименую тогда, действительно не очень подходит название. 
Про return testString.length <= empty; понял, на лайве показывали, но пока плохо ориентируюсь без If else, буду рефакторить, спасибо)

2023-02-24 15:59 UTC, Dima-Dim commented on js/functions.js
> +  return testString.length <= sizeString;
sizeString уже лучше.

2023-02-24 15:59 UTC, merged