8.14 Нерабочий код
htmlacademy-javascript/2138449-kekstagram-28 pull request #6
Opened 2023-03-18 16:18 UTC by RamilJS

2023-03-19 11:05 UTC, Dima-Dim requested changes
> Но возникло две проблемы, дата-атрибуты не задаются, соответственно миниатюры не соотносятся с большой фоткой и вместо нее отрисовывается undefined.

Где ты пробуешь задавать data-атрибуты и как ты пытался понять и решить проблему с тем, что они "не задаются"?

2023-03-19 11:05 UTC, Dima-Dim commented on js/data.js
> +//const generatePhotoId = createRandomIdFromRangeGenerator(1, 25); //Изначально было так
Рамкоментировал тут, закоментировал в `createPhotoDescription` всё продолжило работать.

2023-03-19 11:05 UTC, Dima-Dim commented on js/data.js
> +// Теперь другая проблема, Айдишники повторяются, проверка на уникальность не проходит
У тебя в консоли ошибки:
```Uncaught TypeError: thumbnails.forEarch is not a function```
и
```Uncaught TypeError: document.createFragment is not a function```
Пробовал их решать?

2023-03-19 11:07 UTC, Dima-Dim commented
> генерятся, но почему-то не проходят проверку на уникальность и повторяются

Тоже чуть подробнее, что с чем и где ты ожидаешь одинаковым?

2023-03-20 14:00 UTC, RamilJS commented on js/data.js
> +//const generatePhotoId = createRandomIdFromRangeGenerator(1, 25); //Изначально было так
В этом файле действительно всё работает, но когда вывожу в консоль на main.js функцию createPhotoDescription(), то ID равен null

2023-03-20 15:25 UTC, RamilJS commented on js/data.js
> +// Теперь другая проблема, Айдишники повторяются, проверка на уникальность не проходит
1. thumbnails.forEarch is not a function не понимаю этой ошибки, поскольку thumbnails массив для каждого его элемента выполняю код (возможно опять таки проблема в том, что в массиве ID равен null?);
2. Синтаксис был неправильный, исправил на createDocumentFragment()

2023-03-20 15:29 UTC, RamilJS commented
Дата-атрибуты задаю в файле thumbnail.js 13 cтрока 
humbnail.dataset.thumbnailId = id; // получается, что ID тут равен null 
Возможно они не приклеиваются к разметке из-за того, что ID миниатюры равен null

2023-03-20 18:29 UTC, RamilJS commented
Тоже чуть подробнее, что с чем и где ты ожидаешь одинаковым?

- Как я понимаю: мы генерим ID для фото в функции createPhotoDescription (файл data.js)
- В файле thumbnail.js (11 строка) мы говорим, что дата-атрибут нового DOM-элемента будет равен ID фото (из файла data.js)
- В файле gallery.js (в функции renderGallery) Сравниваем ID миниатюры и дата-атрибут DOM-элемента, вызываем функцию по открытию большой фотки
- То есть ID каждой миниатюры должны, вроде как, совпадать с дата атрибутом DOM-элемента и эта маниатюра должна отрисовываться в большое фото

2023-03-20 23:01 UTC, RamilJS commented on js/data.js
> +// Теперь другая проблема, Айдишники повторяются, проверка на уникальность не проходит
thumbnails.forEarch тоже пофиксил (ошибка была в написании forEach)

2023-03-23 09:49 UTC, Dima-Dim commented on js/data.js
> +//const generatePhotoId = createRandomIdFromRangeGenerator(1, 25); //Изначально было так
Что значит выхожу в консоль? Не нужно писать код в консоли браузера, там нужно смотреть что выдаёт твой код из файлов проекта.

2023-03-23 09:51 UTC, Dima-Dim commented
> Дата-атрибуты задаю в файле thumbnail.js 13 cтрока humbnail.dataset.thumbnailId = id; // получается, что ID тут равен null Возможно они не приклеиваются к разметке из-за того, что ID миниатюры равен null

Ты проверил что он тут null или предположил? Если проверил то дошёл до того места где он становится null, а не тем, чего ты ожидаешь?

2023-03-23 09:55 UTC, Dima-Dim commented
> * кции createPho



> Тоже чуть подробнее, что с чем и где ты ожидаешь одинаковым?
> 
>     * Как я понимаю: мы генерим ID для фото в функции createPhotoDescription (файл data.js)
> 
>     * В файле thumbnail.js (11 строка) мы говорим, что дата-атрибут нового DOM-элемента будет равен ID фото (из файла data.js)
> 
>     * В файле gallery.js (в функции renderGallery) Сравниваем ID миниатюры и дата-атрибут DOM-элемента, вызываем функцию по открытию большой фотки
> 
>     * То есть ID каждой миниатюры должны, вроде как, совпадать с дата атрибутом DOM-элемента и эта маниатюра должна отрисовываться в большое фото

Да, ты описываешь верную логику. Осталось проверить в коде что всё везде приходит именно в том виде, в котором ожидается. А если не в том виде, то выявить ошибку, которая к этому приводит и, хотя бы локализовать её, т.е. понять в каком месте она, в идеале решить.

2023-03-23 15:46 UTC, merged